My Project: sort.h File Reference
sort.h File Reference
#include <stdio.h>
Functions
void bubble_sort (void *data, int start, int end, int(*comp)(const void *, const void *), size_t size)
старая добрая сортировка пузырьком, но уже для любых типов
int string_compare_straight_RUS (const unsigned char *a, const unsigned char *b)
прямое сравнение строк
int sort_strophe_compare_straight_RUS (const void *string1, const void *string2)
обертка для сравнения двух строк
int string_compare_reversed_RUS (const unsigned char *a, int len1, const unsigned char *b, int len2)
обратное двух строк
int sort_strophe_compare_reversed_RUS (const void *string1, const void *string2)
обертка для сравнения двух строк
int string_compare_straight_ENG (const unsigned char *a, const unsigned char *b)
прямое сравнение строк
int sort_strophe_compare_straight_ENG (const void *string1, const void *string2)
обертка для сравнения двух строк
int string_compare_reversed_ENG (const unsigned char *a, int len1, const unsigned char *b, int len2)
обратное двух строк
int sort_strophe_compare_reversed_ENG (const void *string1, const void *string2)
обертка для сравнения двух строк
void merge_sort (void *data, size_t count, int(*comp)(const void *, const void *), size_t size)
сортировка слиянием
Function Documentation
bubble_sort()
void bubble_sort (void * data, int start, int end, int(*)(const void *, const void *) comp, size_t size)
старая добрая сортировка пузырьком, но уже для любых типов
Parameters
data - указатель на начало массива который нужно сортировать
start - с какого эл-та сортировать
end - по какой элемент сортировать
comp - функция сравнения двух элементов
size - размер одного элемента
merge_sort()
void merge_sort (void * data, size_t count, int(*)(const void *, const void *) comp, size_t size)
сортировка слиянием
Parameters
data - указатель на начало массива который нужно сортировать
count - количество элементов
comp - функция сравнения двух элементов
size - размер одного элемента
Referenced by complex_test(), and main().
sort_strophe_compare_reversed_ENG()
int sort_strophe_compare_reversed_ENG (const void * string1, const void * string2)
обертка для сравнения двух строк
Returns
число > или < 0, в зависимости от результата сравнения
sort_strophe_compare_reversed_RUS()
int sort_strophe_compare_reversed_RUS (const void * string1, const void * string2)
обертка для сравнения двух строк
Returns
число > или < 0, в зависимости от результата сравнения
Referenced by complex_test(), and main().
sort_strophe_compare_straight_ENG()
int sort_strophe_compare_straight_ENG (const void * string1, const void * string2)
обертка для сравнения двух строк
Returns
число > или < 0, в зависимости от результата сравнения
sort_strophe_compare_straight_RUS()
int sort_strophe_compare_straight_RUS (const void * string1, const void * string2)
обертка для сравнения двух строк
Returns
число > или < 0, в зависимости от результата сравнения
Referenced by complex_test(), and main().
string_compare_reversed_ENG()
int string_compare_reversed_ENG (const unsigned char * a, int len1, const unsigned char * b, int len2)
обратное двух строк
Returns
число > или < 0, в зависимости от результата сравнения
string_compare_reversed_RUS()
int string_compare_reversed_RUS (const unsigned char * a, int len1, const unsigned char * b, int len2)
обратное двух строк
Returns
число > или < 0, в зависимости от результата сравнения
string_compare_straight_ENG()
int string_compare_straight_ENG (const unsigned char * a, const unsigned char * b)
прямое сравнение строк
Returns
число > или < 0, в зависимости от результата сравнения
string_compare_straight_RUS()
int string_compare_straight_RUS (const unsigned char * a, const unsigned char * b)
прямое сравнение строк
Returns
число > или < 0, в зависимости от результата сравнения